{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f961670a-b41c-4132-a6fc-52ff0c693001",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "      Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "Ans: In Python, the Exception class is the base class for all built-in exceptions, and it provides a set of common methods and \n",
    "     properties that can be used for error handling.\n",
    "    \n",
    "    When creating custom exceptions, it's recommended to derive them from the Exception class (or one of its subclasses) to ensure\n",
    "    that they can be handled using the common error handling mechanisms provided by the language. This is because the built-in error\n",
    "    handling mechanisms in Python, such as try-except blocks, are designed to work with exceptions that inherit from the Exception class.\n",
    "    \n",
    "    Deriving a custom exception class from Exception makes it possible to use the except clause to catch the custom exception, along\n",
    "    with other built-in exceptions. This allows us to write more general-purpose exception handling code that can handle a range of\n",
    "    exception types.\n",
    "    \n",
    "    Therefore, by deriving our custom exception class from the Exception class, we can ensure that it's compatible with the standard\n",
    "    error handling mechanisms in Python, and that it includes the common error handling features that are used throughout the language.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "94c8d951-832e-4e4b-9933-c37dc6aef36f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "# Ans: In Python, all exceptions are derived from the base class Exception. Here is an example Python program to print the exception hierarchy:\n",
    "    \n",
    "def print_exception_hierarchy(exception, level=0):\n",
    "    print(\"|  \" * level + \"+--\" + exception.__name__)\n",
    "    for subclass in exception.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, level + 1)\n",
    "\n",
    "# Print the exception hierarchy\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26e0f177-9dea-4ce5-a40b-34eaf7d90940",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "\n",
    "# Ans: In python \"ArithmaticError\" is a built-in class that is raised when a arithmatic operation fails. It is the base class\n",
    "#       of other exception classes which is related to arithmatic errors.\n",
    "#     Here are some of the errors that are defined in the ArithmeticError class:\n",
    "    \n",
    "#     1 ZeroDivisionError : ZeroDivisionError is raised when a number is divided by zero.\n",
    "    \n",
    "#     Example: In this example, we have defined two variables a and b, and we are trying to divide a by b. Since b is zero, \n",
    "#              the ZeroDivisionError exception is raised, and the program prints an error message \"Error: division by zero\".\n",
    "\n",
    "\n",
    "\n",
    "a = 10\n",
    "b = 0\n",
    "\n",
    "try:\n",
    "    c = a / b\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: division by zero\")\n",
    "\n",
    "    \n",
    "    \n",
    "#     2 OverflowError : This exception is raised when an arithmetic operation results in a number that is too large to be represented.\n",
    "    \n",
    "#     Example:  In this example, we are trying to multiply a number n that is equal to the maximum value that can be represented by a \n",
    "#               variable of type int in Python, plus one. Since n * n is too large to be represented as an integer, the OverflowError \n",
    "#               exception is raised, and the program prints an error message \"Error: overflow\".\n",
    "\n",
    "            \n",
    "import sys\n",
    "\n",
    "try:\n",
    "    n = sys.maxsize + 1\n",
    "    m = n * n\n",
    "except OverflowError:\n",
    "    print(\"Error: overflow\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "303dc48f-f50d-48f7-bb21-5f457dfab3b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "# Ans : LookupError: LookupError is a subclass of \"Exception\" class and base class of saveral built-classes including \n",
    "#                 \"keyError\" and \"IndexError\". It is used as the base class for exception that occur when a key or index\n",
    "#                  is not found in collecion or mapping object. by using lookuperror class we can catch both types of errors\n",
    "#                    using a single except block.\n",
    "        \n",
    "#     1. KeyError: It is the subclass of LookupError class and it raise an exception when trying to non-existing key in a dictionary\n",
    "        \n",
    "#         for example: In this example In the example above, we first try to access the key \"pear\" in the dictionary my_dict.\n",
    "#                     Since \"pear\" is not a key in the dictionary, a KeyError is raised. We catch the exception using a try-except\n",
    "#                     block and print the error message.\n",
    "            \n",
    "my_dict = {\"apple\": 1, \"banana\": 2, \"orange\": 3}\n",
    "try:\n",
    "    value = my_dict[\"pear\"]\n",
    "except KeyError as e:\n",
    "    print(f\"Error key not found : {e}\")\n",
    "\n",
    "#          2. Indexerror: It is the subclass of LookupError class and it raise an exception when trying to acces non-existing index in a\n",
    "#                        list or other sequnce objct\n",
    "         \n",
    "#         for example:  we try to access the element at index 3 in the list my_list. Since my_list only has three elements \n",
    "#                       (with indices 0, 1, and 2), trying to access index 3 will raise an IndexError. We catch the exception  \n",
    "#                       using a try-except block and print the error message.\n",
    "            \n",
    "my_list = [1, 2, 3]\n",
    "try:\n",
    "    value = my_list[3]\n",
    "except IndexError as e:\n",
    "    print(f\"Error: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf18b4e3-ce8c-46be-86ea-53593a2524c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "Ans: ImportError: An ImportError is an Exception and it occur because of the following reasons:\n",
    "    \n",
    "        1 The imported class is in circuler dependency.\n",
    "        2 The imported class is unavailable or was not created.\n",
    "        3 The imported class name is misspelled.\n",
    "        4 The imported class is unavailable in python library\n",
    "        \n",
    "    ModuleNotFoundError : As the name implies, this error occurs when you're trying to access or usea module that cannot\n",
    "                          be found, and it occur because of the following reasons:\n",
    "            \n",
    "        1 the module you tried to importing is not installed on your computer\n",
    "        2 the module name is misspelled.for example : \"numpy\" as \"numpys\"\n",
    "        3 the the casing of module is incorrect. for example: \"numpy\" as \"Numpy\"\n",
    "        4 the path of impoorting the module is wrong\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c47e57f5-ef01-48c1-8cc4-80605ddb3e2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "Ans: the some best practices for exception handling in python are:\n",
    "    \n",
    "    1 use specific exception : Always use specific class instead of using base class. This helps us to identify execr error and handle\n",
    "                             it effectively.\n",
    "        \n",
    "    2 use logging : use logging module to log exception. which helps us to diagnose the issue.\n",
    "     \n",
    "    3 Use finally block : Always use the finally block to perform cleanup operations such as closing files, database connections, etc.,\n",
    "                    regardless of whether an exception was thrown or not.\n",
    "    \n",
    "    4 don't ignore exception : don't ignore exception. Always handle exceptions and make sure your code continues to work correctly, \n",
    "                    even in exceptional circumstances.\n",
    "    \n",
    "    5 keep exception messages simple : Keep the error messages simple and clear, and avoid including sensitive information such as\n",
    "                    passwords or other confidential information.\n",
    "    \n",
    "    6 Test your exception handling code: Test your exception handling code thoroughly to ensure it works as expected and to identify any\n",
    "                    potential issues before your code goes into production."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
